export const departments = {
  Accounting: "ACCTG",
  Journalism: "JOURN",
  "Aerospace Studies": "AERSTU",
  "Judaic Studies": "JUDAIC",
  "Afro-American Studies": "AFROAM",
  "Labor Relations": "LABOR",
  "Animal Science": "ANSCI",
  "Latin American Studies": "LATAM",
  Anthropology: "ANTH",
  Latin: "LATIN",
  Arabic: "ARABIC",
  "Landscape Architecture": "LDARC",
  "Landscape Contracting": "LDCONT",
  Art: "ART",
  "Legal Studies": "LEGAL",
  "Asian Studies": "ASIANS",
  Linguistics: "LING",
  "Learning Support Services": "LSS",
  "Bachelor's Degree with Individual Concentration": "BDIC",
  Mathematics: "MATH",
  "Molecular and Cellular Biology": "MCBIO",
  "Biostatistics and Epidemiology": "BIOEPI",
  "Middle Eastern Studies": "MEAST",
  Biology: "BIOL",
  "Medical Technology": "MEDTEC",
  Biotechnology: "BIOTCH",
  Management: "MGT",
  "Building Materials and Wood Technology": "BMATWT",
  Microbiology: "MICBIO",
  "Civil and Environmental Engineering": "CEE",
  "Mechanical and Industrial Engineering": "MIE",
  "Military Science": "MILSCI",
  Marketing: "MKTG",
  Chemistry: "CHEM",
  "Computer Science": "COMPSCI",
  Music: "MUSIC",
  "Natural Resource Studies": "NAREST",
  "Communication Disorders": "COMDIS",
  Nursing: "NURSE",
  "Comparative Literature": "COMLIT",
  Nutrition: "NUTR",
  "Organismic and Evolutionary Biology": "OEB",
  "Orchard Hill": "OHI",
  "Physical Education": "PE",
  Philosophy: "PHIL",
  Physics: "PHYSIC",
  "Plant Pathology": "PLPATH",
  "Plant and Soil Sciences": "PLSOIL",
  Polish: "POLISH",
  "Political Science": "POLSCI",
  Portuguese: "PORT",
  "Polymer Science and Engineering": "PSE",
  Psychology: "PSYCH",
  "Regional Planning": "REGPL",
  "Resource Economics": "RESEC",
  Russian: "RUSS",
  "Slavic and East European Studies": "SLAVIC",
  Sociology: "SOCIOL",
  "School of Management": "SOM",
  "Food Science": "FDSCI",
  Southwest: "SOWEST",
  Spanish: "SPAN",
  "Sport Studies": "SPORST",
  Statistics: "STATIS",
  "Stockbridge School of Agriculture": "STOCK",
  "Social Thought and Political Economy": "STPEC",
  Swedish: "SWEDSH",
  Theater: "THEATR",
  History: "HIST",
  "University Practicum": "UMASS",
  "Honors Program": "HONORS",
  "University/Interdepartmental": "UNIV",
  "Hotel, Restaurant and Travel Administration": "HRTA",
  "University Without Walls": "UWW",
  "Human Development": "HUMDEV",
  "Wildlife and Fisheries Conservation": "WFCON",
  "Interpreter's Studies": "INTERP",
  "Women's Studies": "WOST",
  Italian: "ITAL",
  Yiddish: "YIDDSH",
  "English Writing Program": "ENGLWP",
  Entomology: "ENT",
  "Environmental Health Sciences": "ENVHL",
  "Environmental Design": "ENVDES",
  "Environmental Sciences": "ENVSCI",
  "English as a Second Language": "ESL",
  "Modern European Studies": "EURO",
  "Exercise Science": "EXCSCI",
  "Five College Foreign Language Resource Center": "FCFLRC",
  "Finance and Operations Management": "FOMGT",
  Forestry: "FOREST",
  "French and Francophone Studies": "FREN",
  Geosciences: "GEO",
  German: "GERMAN",
  Greek: "GREEK",
  Hebrew: "HEBREW",
  Dance: "DANCE",
  Danish: "DANISH",
  Dutch: "DUTCH",
  "Electrical and Computer Engineering": "ECE",
  Economics: "ECON",
  Education: "EDUC",
  Engineering: "ENGIN",
  English: "ENGL",
};

export const reverseDepartment = {
  ACCTG: "Accounting",
  JOURN: "Journalism",
  AERSTU: "Aerospace Studies",
  JUDAIC: "Judaic Studies",
  AFROAM: "Afro-American Studies",
  LABOR: "Labor Relations",
  ANSCI: "Animal Science",
  LATAM: "Latin American Studies",
  ANTH: "Anthropology",
  LATIN: "Latin",
  ARABIC: "Arabic",
  LDARC: "Landscape Architecture",
  LDCONT: "Landscape Contracting",
  ART: "Art",
  LEGAL: "Legal Studies",
  ASIANS: "Asian Studies",
  LING: "Linguistics",
  LSS: "Learning Support Services",
  BDIC: "Bachelor's Degree with Individual Concentration",
  MATH: "Mathematics",
  MCBIO: "Molecular and Cellular Biology",
  BIOEPI: "Biostatistics and Epidemiology",
  MEAST: "Middle Eastern Studies",
  BIOL: "Biology",
  MEDTEC: "Medical Technology",
  BIOTCH: "Biotechnology",
  MGT: "Management",
  BMATWT: "Building Materials and Wood Technology",
  MICBIO: "Microbiology",
  CEE: "Civil and Environmental Engineering",
  MIE: "Mechanical and Industrial Engineering",
  MILSCI: "Military Science",
  MKTG: "Marketing",
  CHEM: "Chemistry",
  COMPSCI: "Computer Science",
  MUSIC: "Music",
  NAREST: "Natural Resource Studies",
  COMDIS: "Communication Disorders",
  NURSE: "Nursing",
  COMLIT: "Comparative Literature",
  NUTR: "Nutrition",
  OEB: "Organismic and Evolutionary Biology",
  OHI: "Orchard Hill",
  PE: "Physical Education",
  PHIL: "Philosophy",
  PHYSIC: "Physics",
  PLPATH: "Plant Pathology",
  PLSOIL: "Plant and Soil Sciences",
  POLISH: "Polish",
  POLSCI: "Political Science",
  PORT: "Portuguese",
  PSE: "Polymer Science and Engineering",
  PSYCH: "Psychology",
  REGPL: "Regional Planning",
  RESEC: "Resource Economics",
  RUSS: "Russian",
  SLAVIC: "Slavic and East European Studies",
  SOCIOL: "Sociology",
  SOM: "School of Management",
  FDSCI: "Food Science",
  SOWEST: "Southwest",
  SPAN: "Spanish",
  SPORST: "Sport Studies",
  STATIS: "Statistics",
  STOCK: "Stockbridge School of Agriculture",
  STPEC: "Social Thought and Political Economy",
  SWEDSH: "Swedish",
  THEATR: "Theater",
  HIST: "History",
  UMASS: "University Practicum",
  HONORS: "Honors Program",
  UNIV: "University/Interdepartmental",
  HRTA: "Hotel, Restaurant and Travel Administration",
  UWW: "University Without Walls",
  HUMDEV: "Human Development",
  WFCON: "Wildlife and Fisheries Conservation",
  INTERP: "Interpreter's Studies",
  WOST: "Women's Studies",
  ITAL: "Italian",
  YIDDSH: "Yiddish",
  ENGLWP: "English Writing Program",
  ENT: "Entomology",
  ENVHL: "Environmental Health Sciences",
  ENVDES: "Environmental Design",
  ENVSCI: "Environmental Sciences",
  ESL: "English as a Second Language",
  EURO: "Modern European Studies",
  EXCSCI: "Exercise Science",
  FCFLRC: "Five College Foreign Language Resource Center",
  FOMGT: "Finance and Operations Management",
  FOREST: "Forestry",
  FREN: "French and Francophone Studies",
  GEO: "Geosciences",
  GERMAN: "German",
  GREEK: "Greek",
  HEBREW: "Hebrew",
  DANCE: "Dance",
  DANISH: "Danish",
  DUTCH: "Dutch",
  ECE: "Electrical and Computer Engineering",
  ECON: "Economics",
  EDUC: "Education",
  ENGIN: "Engineering",
  ENGL: "English",
};

export const departmentOptions = Object.keys(departments);
